### ISSUE TITLE
Повысить консистентность названий и описаний

### ISSUE THREAD

**Issue by x9136** [shikimori/neko-achievements#1106]
Для общего стиля и исходя из смысла — точки в заголовках не нужны, а в описаниях нужны. Полно других моментов, которые стоит поправить, но этот меня парит достаточно сильно, чтобы провести большую часть работы.

Поэтому предлагаю следующие изменения:

**Список аниме • Уровень 10**
| Сейчас | Должно быть |
| ------------- | ------------- |
| It's not even the final form. | It's not even the final form |

**Список аниме • Уровень 13**
_Учтите, что это четверостишие и то, что Раз, Два, Три и Четыре — имена котёнков._
| Сейчас| Должно быть |
| ------------- | ------------- |
| Раз котенок — самый белый Два котенок — самый смелый Три котенок — самый умный А четыре — самый шумный | Раз — котенок самый белый, Два — котенок самый смелый, Три — котенок самый умный, А Четыре — самый шумный. |
| The first kitten is the whitest, The second kitten is the bravest The third kitten is the smartest And the fourth is the noisiest | Kitten One is the whitest, Kitten Two is the bravest, Kitten Three is the smartest, Kitten Four is the noisiest. |

**Цундере • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| It's not what you think. | It's not what you think |

**ГАР • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| So courageous that you can't breathe. | So courageous that you can't breathe |

**Короткометражки • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| A moment, and you lost it. | A moment, and you lost it |

**Махо-сёдзё • Уровень 4**
| Сейчас | Должно быть |
| ------------- | ------------- |
| Your powers allow to change the universe | Your powers allow to change the universe. |

**Меха • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| Get In The Freaking Robot Shinji | Get in the freaking robot, Shinji! |

**Меха • Уровень 4**
_На обоих языках._
| Сейчас | Должно быть |
| ------------- | ------------- |
| ORE WA GUNDAM | ORE WA GUNDAM! |

**Повседневность • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| The average Japanese schoolboy (or schoolgirl). | The average Japanese student |

**Военное • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| Enlisted in the regular draft | Enlisted in the regular draft. |

**Полиция • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| The streets are turbulent. Can't let our guard down | The streets are turbulent. Can't let our guard down. |

**Космос • Уровень 1**
| Сейчас | Должно быть |
| ------------- | ------------- |
| That's one small step for man, one giant leap for mankind | That's one small step for man, one giant leap for mankind. |

**Музыка • Уровень 2**
| Сейчас | Должно быть |
| ------------- | ------------- |
| Where words are powerless. | Where words are powerless |

**Comment by morr** [comment]
звучит логично. если в русском нет, то и в англ варианте точка не нужна
![image](https://github.com/shikimori/neko-achievements/assets/134610/047402e6-8314-4a3d-a42d-21bbc49382a9)

@ReDiskInA @Boogiep0p

**Comment by Boogiep0p** [comment]
Всё, что могу по этому поводу сказать, так это то, что английские варианты полностью заполняли не мы ¯\_(ツ)_/¯

**Comment by x9136** [comment]
> Внешний вид > пунктуация.

У вас там весь смысл стиха Михалкова потерялся, а на английском тем более. Дело ваше, поскольку я не отвечаю за качество текстов на Шикимори и не могу сделать вас требовательными к качеству.

Я пока подожду, а потом если что сам закрою эту проблему, ибо спорить не о чем, а время дорого.

**Comment by Boogiep0p** [comment]
> У вас там весь смысл стиха Михалкова потерялся
И нас это абсолютно не волнует. Цели передать смысл его стихов перед ачивками не стоит.

**Comment by x9136** [comment]
> И нас это абсолютно не волнует. 

Это я уже понял, поэтому больше времени на попытку улучшить Шикимори тратить не собираюсь в вопросе достижений.

**Comment by x9136** [comment]
@morr ты что думаешь? Тебе в целом без разницы какое там качество, отдаешь на откуп пользователям?

**Comment by Boogiep0p** [comment]
> Это времени требует, нужно описывать и обосновывать.

Вы буквально попросили исправить знаки препинания в 11 ачивках, для этого не нужно никакого обоснования и описания, будьте проще)
А что касается котов, то это просто разный творческий подход к тексту. Вы хотите полностью скопировать стих, мы такой задачи перед текстом не ставили и обыгрывали совсем другие вещи.

**Comment by x9136** [comment]
> Вы буквально попросили исправить знаки препинания в 11 ачивках, для этого не нужно никакого обоснования и описания, будьте проще)

Вы говорите о том, о чём не имеете никакого понятия. Я буквально прошёл по всем достижениям из групп «Общие» и «Жанровые» на обоих языках, чтобы проверить их все. Я оформил этот вопрос так, чтобы любому было максимально понятно какие изменения нужно внести и где. Это 1-2 часа работы.

> будьте проще)

Я советов не просил. Поясню свою позицию: если изначально известно, что вам плевать на качество, то мне нет смысла тратить своё время на предложения. Я не хочу вкладываться в то, что в результате будет сделано хреново из-за разницы в подходах.

**Comment by Boogiep0p** [comment]
> Вы говорите о том, о чём не имеете никакого понятия. 

Нисколько не умоляю ваш труд в поиске этих недочётов. Собственно, этот аспект и не упоминался. А вот оформление вы делали зря. Понимаю, что у вас предвзятое мнение о людях, работающих над ачивками, но перечислить уровни было бы достаточно.

> Я не хочу вкладываться в то, что в результате будет сделано хреново из-за разницы в подходах.

Если под "качеством" вы подразумеваете, что ачивки должны быть строго такими, какими вы хотите их видеть, то можете не тратить своё время. Мы осознанно отошли от дословного копирования стиха Михалкова - это отнюдь не наплевательское отношение к тексту ачивки. Вы же, не разбираясь в причинах и следствиях, называете это наплевательским отношением к качеству. По меньшей мере странный поступок.

**Comment by x9136** [comment]
> Вы же, не разбираясь в причинах и следствиях, называете это наплевательским отношением к качеству. По меньшей мере странный поступок.

Ничего странного в этом не вижу, потому что у каждого своё представление о качестве. Я считаю, что у человека есть право считать свои требования к качеству высокими, когда за годы он удосужился исправить хотя бы те мелочи, которые я отметил. Я не могу считать ваше представление о качестве ненаплевательским, учитывая такой срок. Я не сомневаюсь, что остальные фразы, которые требуют редактуры, вы тоже не будете исправлять из-за своего подхода. Увы.

Не тратьте, пожалуйста, моё время на эту фигню. Если у вас остались конкретные вопросы, то спрашивайте и я отвечу.

**Comment by Boogiep0p** [comment]
> Я считаю, что у человека есть право считать свои требования к качеству высокими, когда за годы он удосужился исправить хотя бы те мелочи, которые я отметил. 

Я не вижу причин, принимать вашу критику в свой адрес или адрес других членов клуба, т.к. мы работали только над русскоязычной версией ачивок. Извинений не жду. Всего доброго.

**Comment by x9136** [comment]
@morr короче я закрываю. С одной стороны увы, что работа над сайтом исторически так сложилась, с другой — я легкой ценой узнал причины почему некоторые ошибки живут годами. На мой вопрос можешь не отвечать. Я уверен, что тебя всё устраивает, либо нет времени заниматься улучшениями.
